server:
  port: 8099

spring:
  datasource:
    url: jdbc:h2:mem:testdb # for In-memory persistence
#    url: jdbc:h2:file:/Users/evgenii.shagov/data/demo #for File based persistence
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
#      settings:
#        trace: true
#        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  main:
    banner-mode: off
    # better readable jackson serialization format
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    org.springframework: DEBUG
    eu.shagov: DEBUG



jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

jpa:
  hibernate:
    ddl-auto: create-drop


#    https://github:
#      com/szerhusenBC/jwt-spring-security-demo: